### ISSUE TITLE
第一次运行没有证书提示

### ISSUE THREAD

**Issue by masktao** [miketwes/XX-Net-mini#14]
然后没有继续,不知道为什么,回撤后就退出了
![image](https://user-images.githubusercontent.com/13614353/106624161-53d43e00-65b0-11eb-856c-7275677f8589.png)

**Comment by masktao** [comment]
2021-02-02 23:47:28.649 [launcher][ERROR] launcher except:FileNotFoundError(2, 'No such file or directory')
2021-02-02 23:47:28.650 [launcher][ERROR] Except stack:Traceback (most recent call last):
  File "d:\XX-Net-mini\code\default\launcher\start.py", line 159, in <module>
    main()
  File "d:\XX-Net-mini\code\default\launcher\start.py", line 113, in main
    with open(fname, 'rb') as infile:
FileNotFoundError: [Errno 2] No such file or directory: 'd:\\XX-Net-mini\\data\\gae_proxy\\CA.crt'

Press Enter to continue...

**Comment by miketwes** [comment]
https://github.com/miketwes/XX-Net-mini/issues/12

**Comment by miketwes** [comment]
使用说明:

   Win10_x64: [XX-Net-mini-win10-x64.rar](https://github.com/miketwes/miketwes.github.io/blob/main/file/XX-Net-mini-win10-x64.rar) 集成了最新版本的Python和openssl, 解压后运行start.bat

**Comment by tq01o3n** [comment]
CMD成功访问互联网后有不有频频提示602？

**Comment by miketwes** [comment]
> CMD成功访问互联网后有不有频频提示602？

有时候频频提示602, 没有什么影响, 如果602和 Network is ok, you can start to surf the internet!刷屏再加上网页打不开重启一下start.bat就可以解决问题

**Comment by tq01o3n** [comment]
> > CMD成功访问互联网后有不有频频提示602？
> 
> 有时候频频提示602, 没有什么影响, 如果602和 Network is ok, you can start to surf the internet!刷屏再加上网页打不开重启一下start.bat就可以解决问题

要是重启start.bat还是频频602呢?网页依然打开缓慢

**Comment by miketwes** [comment]
> 重启start.bat

重启start.bat是解决网页打不开问题,  不是解决602问题

**Comment by miketwes** [comment]
有两种版本，不会安装Python和openssl的网友可选择下载[XX-Net-mini-win10-x64.rar](https://github.com/miketwes/miketwes.github.io/raw/main/file/XX-Net-mini-win10-x64.rar)

**Comment by ShadowEmbrace** [comment]
> 
> 
> 有两种版本，不会安装Python和openssl的网友可选择下载[XX-Net-mini-win10-x64.rar](https://github.com/miketwes/miketwes.github.io/raw/main/file/XX-Net-mini-win10-x64.rar)

这个空了。。。

**Comment by masktao** [comment]
> #12

后来加了环境变量,也就是设置个路径,问题依旧
`OpenSSL 1.1.1i  8 Dec 2020
Python 3.9.1

2021-03-12 07:09:17.514 [launcher][ERROR] launcher except:FileNotFoundError(2, 'No such file or directory')
2021-03-12 07:09:17.515 [launcher][ERROR] Except stack:Traceback (most recent call last):
  File "d:\XX-Net-mini\code\default\launcher\start.py", line 160, in <module>
    main()
  File "d:\XX-Net-mini\code\default\launcher\start.py", line 114, in main
    with open(fname, 'rb') as infile:
FileNotFoundError: [Errno 2] No such file or directory: 'd:\\XX-Net-mini\\data\\gae_proxy\\CA.crt'

Press Enter to continue...`
![image](https://user-images.githubusercontent.com/13614353/110868007-bbde1880-8302-11eb-9d13-a63915a06406.png)

而且发现上面"FileNotFoundError:"这行路径是双斜杠,但回帖后显示但斜杠

**Comment by miketwes** [comment]
> > #12
> 
> 后来加了环境变量,也就是设置个路径,问题依旧
> `OpenSSL 1.1.1i 8 Dec 2020
> Python 3.9.1
> 
> 2021-03-12 07:09:17.514 [launcher][ERROR] launcher except:FileNotFoundError(2, 'No such file or directory')
> 2021-03-12 07:09:17.515 [launcher][ERROR] Except stack:Traceback (most recent call last):
> File "d:\XX-Net-mini\code\default\launcher\start.py", line 160, in
> main()
> File "d:\XX-Net-mini\code\default\launcher\start.py", line 114, in main
> with open(fname, 'rb') as infile:
> FileNotFoundError: [Errno 2] No such file or directory: 'd:\XX-Net-mini\data\gae_proxy\CA.crt'
> 
> Press Enter to continue...`
> ![image](https://user-images.githubusercontent.com/13614353/110868007-bbde1880-8302-11eb-9d13-a63915a06406.png)
> 
> 而且发现上面"FileNotFoundError:"这行路径是双斜杠,但回帖后显示但斜杠

可选择下载[XX-Net-mini-win10-x64.rar](https://github.com/miketwes/miketwes.github.io/raw/main/file/XX-Net-mini-win10-x64.rar), 解压后直接运行start.bat

**Comment by masktao** [comment]
> > > #12
> > 
> > 
> > 后来加了环境变量,也就是设置个路径,问题依旧
> > `OpenSSL 1.1.1i 8 Dec 2020
> > Python 3.9.1
> > 2021-03-12 07:09:17.514 [launcher][ERROR] launcher except:FileNotFoundError(2, 'No such file or directory')
> > 2021-03-12 07:09:17.515 [launcher][ERROR] Except stack:Traceback (most recent call last):
> > File "d:\XX-Net-mini\code\default\launcher\start.py", line 160, in
> > main()
> > File "d:\XX-Net-mini\code\default\launcher\start.py", line 114, in main
> > with open(fname, 'rb') as infile:
> > FileNotFoundError: [Errno 2] No such file or directory: 'd:\XX-Net-mini\data\gae_proxy\CA.crt'
> > Press Enter to continue...`
> > ![image](https://user-images.githubusercontent.com/13614353/110868007-bbde1880-8302-11eb-9d13-a63915a06406.png)
> > 而且发现上面"FileNotFoundError:"这行路径是双斜杠,但回帖后显示但斜杠
> 
> 可选择下载[XX-Net-mini-win10-x64.rar](https://github.com/miketwes/miketwes.github.io/raw/main/file/XX-Net-mini-win10-x64.rar), 解压后直接运行start.bat

奇了怪了,昨天下载的运行会提示的错误,刚才用重新下载解压可以直接运行,没有提示错误.但是还无法连接
防火墙通过了,关了都没用..浏览器代理本身SwitchyOmega配置好了xx-net所以不用改,但貌似翻不出去.用自己的id也一样
![image](https://user-images.githubusercontent.com/13614353/110926319-32106880-835f-11eb-916e-1c2c214b0473.png)

**Comment by miketwes** [comment]
> > > > #12
> > > 
> > > 
> > > 后来加了环境变量,也就是设置个路径,问题依旧
> > > `OpenSSL 1.1.1i 8 Dec 2020 Python 3.9.1 2021-03-12 07:09:17.514 [launcher][ERROR] launcher except:FileNotFoundError(2, 'No such file or directory') 2021-03-12 07:09:17.515 [launcher][ERROR] Except stack:Traceback (most recent call last): File "d:\XX-Net-mini\code\default\launcher\start.py", line 160, in main() File "d:\XX-Net-mini\code\default\launcher\start.py", line 114, in main with open(fname, 'rb') as infile: FileNotFoundError: [Errno 2] No such file or directory: 'd:\XX-Net-mini\data\gae_proxy\CA.crt' Press Enter to continue...`
> > > ![image](https://user-images.githubusercontent.com/13614353/110868007-bbde1880-8302-11eb-9d13-a63915a06406.png)
> > > 而且发现上面"FileNotFoundError:"这行路径是双斜杠,但回帖后显示但斜杠
> > 
> > 
> > 可选择下载[XX-Net-mini-win10-x64.rar](https://github.com/miketwes/miketwes.github.io/raw/main/file/XX-Net-mini-win10-x64.rar), 解压后直接运行start.bat
> 
> 奇了怪了,昨天下载的运行会提示的错误,刚才用重新下载解压可以直接运行,没有提示错误.但是还无法连接
> 防火墙通过了,关了都没用..浏览器代理本身SwitchyOmega配置好了xx-net所以不用改,但貌似翻不出去.用自己的id也一样
> ![image](https://user-images.githubusercontent.com/13614353/110926319-32106880-835f-11eb-916e-1c2c214b0473.png)

访问其他网站是什么提示？我这里正常访问

![2021-03-12_671x572](https://user-images.githubusercontent.com/6849681/110949856-123c6d00-837e-11eb-8cd6-eba6b5f026b3.png)

**Comment by masktao** [comment]
访问谷歌出现如下提示,貌似证书问题,但证书已经自动导入了
![image](https://user-images.githubusercontent.com/13614353/111017701-025d7100-83f0-11eb-82a8-d671bedd7ebb.png)

**Comment by miketwes** [comment]
> 访问谷歌出现如下提示,貌似证书问题,但证书已经自动导入了
> ![image](https://user-images.githubusercontent.com/13614353/111017701-025d7100-83f0-11eb-82a8-d671bedd7ebb.png)

打开win10证书管理，在受信任的根证书里看有没有XX-Net-mini相关的证书, 如果有, 删除再导入XX-Net-mini-win10-x64\data\gae_proxy\CA.crt，如果没有，选择导入 XX-Net-mini-win10-x64\data\gae_proxy\CA.crt

看看Chrome证书Authourity里看有没有XX-Net-mini相关的证书, 如果有, 删除再导入XX-Net-mini-win10-x64\data\gae_proxy\CA.crt，如果没有，选择导入 XX-Net-mini-win10-x64\data\gae_proxy\CA.crt

**Comment by masktao** [comment]
> > 访问谷歌出现如下提示,貌似证书问题,但证书已经自动导入了
> > ![image](https://user-images.githubusercontent.com/13614353/111017701-025d7100-83f0-11eb-82a8-d671bedd7ebb.png)
> 
> 打开win10证书管理，在受信任的根证书里看有没有XX-Net-mini相关的证书, 如果有, 删除再导入XX-Net-mini-win10-x64\data\gae_proxy\CA.crt，如果没有，选择导入 XX-Net-mini-win10-x64\data\gae_proxy\CA.crt
> 
> 看看Chrome证书Authourity里看有没有XX-Net-mini相关的证书, 如果有, 删除再导入XX-Net-mini-win10-x64\data\gae_proxy\CA.crt，如果没有，选择导入 XX-Net-mini-win10-x64\data\gae_proxy\CA.crt

下午就重新导过,没什么效果.发现证书是4.5.3的版本? 难道不是4.5.2? 这个证书和xx-net都堆一起了
![image](https://user-images.githubusercontent.com/13614353/111030452-475bc480-843d-11eb-97e9-4793ac4a9c00.png)

**Comment by miketwes** [comment]
> > > 访问谷歌出现如下提示,貌似证书问题,但证书已经自动导入了
> > > ![image](https://user-images.githubusercontent.com/13614353/111017701-025d7100-83f0-11eb-82a8-d671bedd7ebb.png)
> > 
> > 
> > 打开win10证书管理，在受信任的根证书里看有没有XX-Net-mini相关的证书, 如果有, 删除再导入XX-Net-mini-win10-x64\data\gae_proxy\CA.crt，如果没有，选择导入 XX-Net-mini-win10-x64\data\gae_proxy\CA.crt
> > 看看Chrome证书Authourity里看有没有XX-Net-mini相关的证书, 如果有, 删除再导入XX-Net-mini-win10-x64\data\gae_proxy\CA.crt，如果没有，选择导入 XX-Net-mini-win10-x64\data\gae_proxy\CA.crt
> 
> 下午就重新导过,没什么效果.发现证书是4.5.3的版本? 难道不是4.5.2? 这个证书和xx-net都堆一起了
> ![image](https://user-images.githubusercontent.com/13614353/111030452-475bc480-843d-11eb-97e9-4793ac4a9c00.png)


证书是XX-Net-mini 4.5.2的, 名字是4.5.3

看看Chrome证书Authourity里看有没有XX-Net-mini相关的证书, 如果有, 删除再导入XX-Net-mini-win10-x64\data\gae_proxy\CA.crt，如果没有，选择导入 XX-Net-mini-win10-x64\data\gae_proxy\CA.crt

![2021-03-13_414x674](https://user-images.githubusercontent.com/6849681/111031686-b89e7600-8443-11eb-88de-710ef032cc9a.png)

**Comment by masktao** [comment]
> > > > 访问谷歌出现如下提示,貌似证书问题,但证书已经自动导入了
> > > > ![image](https://user-images.githubusercontent.com/13614353/111017701-025d7100-83f0-11eb-82a8-d671bedd7ebb.png)
> > > 
> > > 
> > > 打开win10证书管理，在受信任的根证书里看有没有XX-Net-mini相关的证书, 如果有, 删除再导入XX-Net-mini-win10-x64\data\gae_proxy\CA.crt，如果没有，选择导入 XX-Net-mini-win10-x64\data\gae_proxy\CA.crt
> > > 看看Chrome证书Authourity里看有没有XX-Net-mini相关的证书, 如果有, 删除再导入XX-Net-mini-win10-x64\data\gae_proxy\CA.crt，如果没有，选择导入 XX-Net-mini-win10-x64\data\gae_proxy\CA.crt
> > 
> > 
> > 下午就重新导过,没什么效果.发现证书是4.5.3的版本? 难道不是4.5.2? 这个证书和xx-net都堆一起了
> > ![image](https://user-images.githubusercontent.com/13614353/111030452-475bc480-843d-11eb-97e9-4793ac4a9c00.png)
> 
> 证书是XX-Net-mini 4.5.2的, 名字是4.5.3
> 
> 看看Chrome证书Authourity里看有没有XX-Net-mini相关的证书, 如果有, 删除再导入XX-Net-mini-win10-x64\data\gae_proxy\CA.crt，如果没有，选择导入 XX-Net-mini-win10-x64\data\gae_proxy\CA.crt
> 
> ![2021-03-13_414x674](https://user-images.githubusercontent.com/6849681/111031686-b89e7600-8443-11eb-88de-710ef032cc9a.png)

chrome://settings//certifitaes

> > > > 访问谷歌出现如下提示,貌似证书问题,但证书已经自动导入了
> > > > ![image](https://user-images.githubusercontent.com/13614353/111017701-025d7100-83f0-11eb-82a8-d671bedd7ebb.png)
> > > 
> > > 
> > > 打开win10证书管理，在受信任的根证书里看有没有XX-Net-mini相关的证书, 如果有, 删除再导入XX-Net-mini-win10-x64\data\gae_proxy\CA.crt，如果没有，选择导入 XX-Net-mini-win10-x64\data\gae_proxy\CA.crt
> > > 看看Chrome证书Authourity里看有没有XX-Net-mini相关的证书, 如果有, 删除再导入XX-Net-mini-win10-x64\data\gae_proxy\CA.crt，如果没有，选择导入 XX-Net-mini-win10-x64\data\gae_proxy\CA.crt
> > 
> > 
> > 下午就重新导过,没什么效果.发现证书是4.5.3的版本? 难道不是4.5.2? 这个证书和xx-net都堆一起了
> > ![image](https://user-images.githubusercontent.com/13614353/111030452-475bc480-843d-11eb-97e9-4793ac4a9c00.png)
> 
> 证书是XX-Net-mini 4.5.2的, 名字是4.5.3
> 
> 看看Chrome证书Authourity里看有没有XX-Net-mini相关的证书, 如果有, 删除再导入XX-Net-mini-win10-x64\data\gae_proxy\CA.crt，如果没有，选择导入 XX-Net-mini-win10-x64\data\gae_proxy\CA.crt
> 
> ![2021-03-13_414x674](https://user-images.githubusercontent.com/6849681/111031686-b89e7600-8443-11eb-88de-710ef032cc9a.png)

你这个操作页面chrome://settings//certifitaes. 我这边浏览器打不开,两个浏览器都没这个页面设置
而且我记得除了firfox有独立的证书管理. chrome的证书管理调用的就是win10 ie自带的证书管理.所以系统也好,chrome也好,设置一个就够了
你上面说的Chrome证书Authourity..我每次导入就是root栏,和xx-net证书在一起
![image](https://user-images.githubusercontent.com/13614353/111035352-14252f80-8455-11eb-9591-8b6c6c948932.png)

第一次运行自动安装,手动安装.管理员权限安装几次.没效果. xx-net的证书没遇到过这种情况

**Comment by miketwes** [comment]
CSDN的一篇文章，建议阅读一下:

解决Chrome浏览器不能访问https网站的问题

使用Chrome访问https网站时，可能会出现以下错误，本文说明如何解决此类问题:
“您的连接不是私密连接”、“NET::ERR_CERT_AUTHORITY_INVALID”、“ERR_CERT_COMMON_NAME_INVALID”或“NET::ERR_CERT_WEAK_SIGNATURE_ALGORITHM”

方法/步骤：
```
1、参考下面经验，将Chrome升级到最新版本https://www.google.cn/chrome/，看是否可以解决这些问题，如果问题没有解决
2、找到Chrome浏览器的快捷方式，选中该快捷方式，按下鼠标右键，在弹出菜单中选择"属性"
3、在弹出的属性对话框中选择"快捷方式"页签，在目标中加入如下起动参数： --test-type --ignore-certificate-errors，点确定按钮
```

注意：在chrome.exe和参数之间需要加一个空格后,开启Chrome浏览器，再次浏览之前出错的https网站，问题应该已经消失
如果出现如下提示，那是因为在步骤3中的起动参数中少加了--test--type
`您使用的是不受支持的命令行标记–ignore-certificate-errors 稳定性和安全性会有所下降`

如果网页提示不安全，不能正确加载，点击地址栏开头，进网站设置-不安全内容-允许

**Comment by masktao** [comment]
> CSDN的一篇文章，建议阅读一下:
> 
> 解决Chrome浏览器不能访问https网站的问题
> 
> 使用Chrome访问https网站时，可能会出现以下错误，本文说明如何解决此类问题:
> “您的连接不是私密连接”、“NET::ERR_CERT_AUTHORITY_INVALID”、“ERR_CERT_COMMON_NAME_INVALID”或“NET::ERR_CERT_WEAK_SIGNATURE_ALGORITHM”
> 
> 方法/步骤：
> 
> ```
> 1、参考下面经验，将Chrome升级到最新版本https://www.google.cn/chrome/，看是否可以解决这些问题，如果问题没有解决
> 2、找到Chrome浏览器的快捷方式，选中该快捷方式，按下鼠标右键，在弹出菜单中选择"属性"
> 3、在弹出的属性对话框中选择"快捷方式"页签，在目标中加入如下起动参数： --test-type --ignore-certificate-errors，点确定按钮
> ```
> 
> 注意：在chrome.exe和参数之间需要加一个空格后,开启Chrome浏览器，再次浏览之前出错的https网站，问题应该已经消失
> 如果出现如下提示，那是因为在步骤3中的起动参数中少加了--test--type
> `您使用的是不受支持的命令行标记–ignore-certificate-errors 稳定性和安全性会有所下降`
> 
> 如果网页提示不安全，不能正确加载，点击地址栏开头，进网站设置-不安全内容-允许

浏览器本身有忽略证书提示选项,选上之后,youtube可以开了,但速度不如xx-net,不知道是没有设置ip还是优化问题
问题果然还是在证书上,xx-net的证书怎么就没出过问题
![image](https://user-images.githubusercontent.com/13614353/111057381-15407600-84c2-11eb-93b4-2c9d420d92f3.png)
另外对比了下mini 和xx-net运行是的内存占用,感觉差不多
![image](https://user-images.githubusercontent.com/13614353/111057401-386b2580-84c2-11eb-864e-74cbeb0429f6.png)

**Comment by miketwes** [comment]
> > CSDN的一篇文章，建议阅读一下:
> > 解决Chrome浏览器不能访问https网站的问题
> > 使用Chrome访问https网站时，可能会出现以下错误，本文说明如何解决此类问题:
> > “您的连接不是私密连接”、“NET::ERR_CERT_AUTHORITY_INVALID”、“ERR_CERT_COMMON_NAME_INVALID”或“NET::ERR_CERT_WEAK_SIGNATURE_ALGORITHM”
> > 方法/步骤：
> > ```
> > 1、参考下面经验，将Chrome升级到最新版本https://www.google.cn/chrome/，看是否可以解决这些问题，如果问题没有解决
> > 2、找到Chrome浏览器的快捷方式，选中该快捷方式，按下鼠标右键，在弹出菜单中选择"属性"
> > 3、在弹出的属性对话框中选择"快捷方式"页签，在目标中加入如下起动参数： --test-type --ignore-certificate-errors，点确定按钮
> > ```
> > 
> > 
> > 注意：在chrome.exe和参数之间需要加一个空格后,开启Chrome浏览器，再次浏览之前出错的https网站，问题应该已经消失
> > 如果出现如下提示，那是因为在步骤3中的起动参数中少加了--test--type
> > `您使用的是不受支持的命令行标记–ignore-certificate-errors 稳定性和安全性会有所下降`
> > 如果网页提示不安全，不能正确加载，点击地址栏开头，进网站设置-不安全内容-允许
> 
> 浏览器本身有忽略证书提示选项,选上之后,youtube可以开了,但速度不如xx-net,不知道是没有设置ip还是优化问题
> 问题果然还是在证书上,xx-net的证书怎么就没出过问题
> ![image](https://user-images.githubusercontent.com/13614353/111057381-15407600-84c2-11eb-93b4-2c9d420d92f3.png)
> 另外对比了下mini 和xx-net运行是的内存占用,感觉差不多
> ![image](https://user-images.githubusercontent.com/13614353/111057401-386b2580-84c2-11eb-864e-74cbeb0429f6.png)

没有在Win10下用过xx-net, 有机会体验一下, 看看有什么问题

**Comment by miketwes** [comment]
> 浏览器本身有忽略证书提示选项,选上之后,youtube可以开了,但速度不如xx-net,不知道是没有设置ip还是优化问题
> 问题果然还是在证书上,xx-net的证书怎么就没出过问题

证书问题已解决, 欢迎测试并提出宝贵意见
