### ISSUE TITLE
找不到module

### ISSUE THREAD

**Issue by fantasyado** [miketwes/XX-Net-mini#15]
****************************************
XX-Net-mini
****************************************

Microsoft Windows [版本 10.0.19041.867]
SystemType
x64-based PC

OpenSSL 1.1.1k-dev  xx XXX xxxx
Python 3.8.3

2021-04-03 12:19:43.819 [launcher][ERROR] start module gae_proxy fail:No module named '_brotli'
2021-04-03 12:19:43.830 [launcher][ERROR] Except stack:Traceback (most recent call last):
  File "F:\soft\system\XX-Net-mini-master\code\default\launcher\module_init.py", line 30, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local'], 0)
  File "F:\soft\system\XX-Net-mini-master\code\default\gae_proxy\local\__init__.py", line 2, in <module>
    from . import apis
  File "F:\soft\system\XX-Net-mini-master\code\default\gae_proxy\local\apis.py", line 2, in <module>
    from .front import front, direct_front
  File "F:\soft\system\XX-Net-mini-master\code\default\gae_proxy\local\front.py", line 15, in <module>
    from front_base.http_dispatcher import HttpsDispatcher
  File "F:\soft\system\XX-Net-mini-master\code\default\lib\front_base\http_dispatcher.py", line 29, in <module>
    from .http2_connection import Http2Worker
  File "F:\soft\system\XX-Net-mini-master\code\default\lib\front_base\http2_connection.py", line 9, in <module>
    from hyper.common.bufsocket import BufferedSocket
  File "F:\soft\system\XX-Net-mini-master\code\default\lib\hyper\__init__.py", line 11, in <module>
    from .common.connection import HTTPConnection
  File "F:\soft\system\XX-Net-mini-master\code\default\lib\hyper\common\connection.py", line 9, in <module>
    from ..http11.connection import HTTP11Connection
  File "F:\soft\system\XX-Net-mini-master\code\default\lib\hyper\http11\connection.py", line 18, in <module>
    from .response import HTTP11Response
  File "F:\soft\system\XX-Net-mini-master\code\default\lib\hyper\http11\response.py", line 12, in <module>
    import brotli
  File "F:\soft\system\XX-Net-mini-master\code\default\lib\brotli.py", line 8, in <module>
    import _brotli
ModuleNotFoundError: No module named '_brotli'

2021-04-03 12:19:43.831 [launcher][ERROR] launcher except:ModuleNotFoundError("No module named '_brotli'")
2021-04-03 12:19:43.832 [launcher][ERROR] Except stack:Traceback (most recent call last):
  File "start.py", line 159, in <module>
    main()
  File "start.py", line 150, in main
    module_init.start_all_auto()
  File "F:\soft\system\XX-Net-mini-master\code\default\launcher\module_init.py", line 103, in start_all_auto
    start(module)
  File "F:\soft\system\XX-Net-mini-master\code\default\launcher\module_init.py", line 30, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local'], 0)
  File "F:\soft\system\XX-Net-mini-master\code\default\gae_proxy\local\__init__.py", line 2, in <module>
    from . import apis
  File "F:\soft\system\XX-Net-mini-master\code\default\gae_proxy\local\apis.py", line 2, in <module>
    from .front import front, direct_front
  File "F:\soft\system\XX-Net-mini-master\code\default\gae_proxy\local\front.py", line 15, in <module>
    from front_base.http_dispatcher import HttpsDispatcher
  File "F:\soft\system\XX-Net-mini-master\code\default\lib\front_base\http_dispatcher.py", line 29, in <module>
    from .http2_connection import Http2Worker
  File "F:\soft\system\XX-Net-mini-master\code\default\lib\front_base\http2_connection.py", line 9, in <module>
    from hyper.common.bufsocket import BufferedSocket
  File "F:\soft\system\XX-Net-mini-master\code\default\lib\hyper\__init__.py", line 11, in <module>
    from .common.connection import HTTPConnection
  File "F:\soft\system\XX-Net-mini-master\code\default\lib\hyper\common\connection.py", line 9, in <module>
    from ..http11.connection import HTTP11Connection
  File "F:\soft\system\XX-Net-mini-master\code\default\lib\hyper\http11\connection.py", line 18, in <module>
    from .response import HTTP11Response
  File "F:\soft\system\XX-Net-mini-master\code\default\lib\hyper\http11\response.py", line 12, in <module>
    import brotli
  File "F:\soft\system\XX-Net-mini-master\code\default\lib\brotli.py", line 8, in <module>
    import _brotli
ModuleNotFoundError: No module named '_brotli'

**Comment by fantasyado** [comment]
pip install brotli
