### ISSUE TITLE
 network IPv6 fail 怎么设置

### ISSUE THREAD

**Issue by fantasyado** [miketwes/XX-Net-mini#16]
2021-04-03 12:42:14.751 [gae_proxy][INFO] SSL use version:TLSv1_3
2021-04-03 12:42:14.753 [gae_proxy][INFO] OpenSSL support alpn
2021-04-03 12:42:14.766 [gae_proxy][INFO] load ip_list num:707, target num:707
2021-04-03 12:42:14.772 [gae_proxy][INFO] SSL use version:TLSv1_3
2021-04-03 12:42:14.774 [gae_proxy][INFO] server 127.0.0.1:8087 started.
2021-04-03 12:42:14.850 [launcher][INFO] module gae_proxy started
2021-04-03 12:42:14.887 [smart_router][INFO] Load file:F:\soft\system\XX-Net-mini-master\code\default\smart_router\local\gfw_black_list.txt
2021-04-03 12:42:14.903 [smart_router][INFO] Load file:F:\soft\system\XX-Net-mini-master\code\default\smart_router\local\gfw_white_list.txt
2021-04-03 12:42:14.905 [smart_router][INFO] Load file:F:\soft\system\XX-Net-mini-master\code\default\smart_router\local\advertisement_list.txt
2021-04-03 12:42:14.921 [smart_router][INFO] Local DNS server:8.8.8.8
2021-04-03 12:42:14.922 [smart_router][INFO] Local DNS server:114.114.114.114
2021-04-03 12:42:14.923 [smart_router][INFO] server 127.0.0.1:8086 started.
2021-04-03 12:42:14.924 [smart_router][INFO] Proxy server listen:['127.0.0.1']:8086.
2021-04-03 12:42:14.924 [smart_router][INFO] start DNS server at 127.0.0.1:53
2021-04-03 12:42:14.988 [launcher][INFO] module smart_router started
2021-04-03 12:42:19.053 [gae_proxy][WARNING] network IPv6 fail

**Comment by miketwes** [comment]
可以先不用任何隧道直接访问https://ipv6.vm3.test-ipv6.com/, 测试IPv6 连接:

![2021-04-08_567x160](https://user-images.githubusercontent.com/6849681/113961150-2b8ae900-9858-11eb-9821-f42561865e8d.png)

如果测试网站IPv6状况评分不是10／10, 可以考虑使用[hurricane electric](https://tunnelbroker.net/)(推荐)等在线隧道以确保测试网站IPv6状况评分10／10

teredo隧道(有可能已经关闭服务, 不推荐)可参考:
* [IPv6 Win10](https://github.com/XX-net/XX-Net/wiki/IPv6-Win10)
* [Win10开启IPv6基于Teredo 隧道（最新、有效解决之道！）](https://cloud.tencent.com/developer/article/1415661)
* [win10通过开启teredo访问ipv6](https://blog.csdn.net/ying86615791/article/details/79031070)

**Comment by fantasyado** [comment]
按照教程设置了一下v6 在那个测试网站是 0/10 但是控制台报的错不一样了

2021-04-14 22:17:28.557 [gae_proxy][INFO] SSL use version:TLSv1_3
2021-04-14 22:17:28.569 [gae_proxy][INFO] OpenSSL support alpn
2021-04-14 22:17:28.601 [gae_proxy][INFO] load ip_list num:707, target num:707
2021-04-14 22:17:28.608 [gae_proxy][INFO] SSL use version:TLSv1_3
2021-04-14 22:17:28.610 [gae_proxy][INFO] server 127.0.0.1:8087 started.
2021-04-14 22:17:28.657 [launcher][INFO] module gae_proxy started
2021-04-14 22:17:28.705 [smart_router][INFO] Load file:F:\soft\system\XX-Net-mini-master\code\default\smart_router\local\gfw_black_list.txt
2021-04-14 22:17:28.728 [smart_router][INFO] Load file:F:\soft\system\XX-Net-mini-master\code\default\smart_router\local\gfw_white_list.txt
2021-04-14 22:17:28.735 [smart_router][INFO] Load file:F:\soft\system\XX-Net-mini-master\code\default\smart_router\local\advertisement_list.txt
2021-04-14 22:17:28.760 [smart_router][INFO] Local DNS server:8.8.8.8
2021-04-14 22:17:28.761 [smart_router][INFO] Local DNS server:114.114.114.114
2021-04-14 22:17:28.763 [smart_router][INFO] server 127.0.0.1:8086 started.
2021-04-14 22:17:28.764 [smart_router][INFO] Proxy server listen:['127.0.0.1']:8086.
2021-04-14 22:17:28.765 [smart_router][INFO] start DNS server at 127.0.0.1:53
2021-04-14 22:17:28.806 [launcher][INFO] module smart_router started
2021-04-14 22:18:05.012 [smart_router][DEBUG] connect to www.google.com:443 from:127.0.0.1:3302
2021-04-14 22:18:05.013 [smart_router][ERROR] any err:AttributeError("'NoneType' object has no attribute 'get_rule'")
2021-04-14 22:18:05.015 [smart_router][DEBUG] connect to www.google.com:443 from:127.0.0.1:3303
2021-04-14 22:18:05.015 [smart_router][ERROR] any err:AttributeError("'NoneType' object has no attribute 'get_rule'")
2021-04-14 22:18:05.032 [smart_router][ERROR] Except stack:Traceback (most recent call last):
  File "F:\soft\system\XX-Net-mini-master\code\default\smart_router\local\proxy_handler.py", line 71, in handle
    self.https_handler()
  File "F:\soft\system\XX-Net-mini-master\code\default\smart_router\local\proxy_handler.py", line 308, in https_handler
    handle_domain_proxy(sock, host, port, self.client_address)
  File "F:\soft\system\XX-Net-mini-master\code\default\smart_router\local\smart_route.py", line 538, in handle_domain_proxy
    rule = g.domain_cache.get_rule(host)
AttributeError: 'NoneType' object has no attribute 'get_rule'

2021-04-14 22:18:05.034 [smart_router][ERROR] Except stack:Traceback (most recent call last):
  File "F:\soft\system\XX-Net-mini-master\code\default\smart_router\local\proxy_handler.py", line 71, in handle
    self.https_handler()
  File "F:\soft\system\XX-Net-mini-master\code\default\smart_router\local\proxy_handler.py", line 308, in https_handler
    handle_domain_proxy(sock, host, port, self.client_address)
  File "F:\soft\system\XX-Net-mini-master\code\default\smart_router\local\smart_route.py", line 538, in handle_domain_proxy
    rule = g.domain_cache.get_rule(host)
AttributeError: 'NoneType' object has no attribute 'get_rule'

2021-04-14 22:18:05.038 [smart_router][DEBUG] connect to www.google.com:443 from:127.0.0.1:3304
2021-04-14 22:18:05.038 [smart_router][DEBUG] connect to www.google.com:443 from:127.0.0.1:3305
2021-04-14 22:18:05.039 [smart_router][ERROR] any err:AttributeError("'NoneType' object has no attribute 'get_rule'")
2021-04-14 22:18:05.040 [smart_router][ERROR] any err:AttributeError("'NoneType' object has no attribute 'get_rule'")
2021-04-14 22:18:05.040 [smart_router][ERROR] Except stack:Traceback (most recent call last):
  File "F:\soft\system\XX-Net-mini-master\code\default\smart_router\local\proxy_handler.py", line 71, in handle
    self.https_handler()
  File "F:\soft\system\XX-Net-mini-master\code\default\smart_router\local\proxy_handler.py", line 308, in https_handler
    handle_domain_proxy(sock, host, port, self.client_address)
  File "F:\soft\system\XX-Net-mini-master\code\default\smart_router\local\smart_route.py", line 538, in handle_domain_proxy
    rule = g.domain_cache.get_rule(host)
AttributeError: 'NoneType' object has no attribute 'get_rule'

2021-04-14 22:18:05.042 [smart_router][ERROR] Except stack:Traceback (most recent call last):
  File "F:\soft\system\XX-Net-mini-master\code\default\smart_router\local\proxy_handler.py", line 71, in handle
    self.https_handler()
  File "F:\soft\system\XX-Net-mini-master\code\default\smart_router\local\proxy_handler.py", line 308, in https_handler
    handle_domain_proxy(sock, host, port, self.client_address)
  File "F:\soft\system\XX-Net-mini-master\code\default\smart_router\local\smart_route.py", line 538, in handle_domain_proxy
    rule = g.domain_cache.get_rule(host)
AttributeError: 'NoneType' object has no attribute 'get_rule'

2021-04-14 22:18:05.160 [smart_router][DEBUG] connect to api.mousegesturesapi.com:443 from:127.0.0.1:3307
2021-04-14 22:18:05.161 [smart_router][ERROR] any err:AttributeError("'NoneType' object has no attribute 'get_rule'")
2021-04-14 22:18:05.162 [smart_router][ERROR] Except stack:Traceback (most recent call last):
  File "F:\soft\system\XX-Net-mini-master\code\default\smart_router\local\proxy_handler.py", line 71, in handle
    self.https_handler()
  File "F:\soft\system\XX-Net-mini-master\code\default\smart_router\local\proxy_handler.py", line 308, in https_handler
    handle_domain_proxy(sock, host, port, self.client_address)
  File "F:\soft\system\XX-Net-mini-master\code\default\smart_router\local\smart_route.py", line 538, in handle_domain_proxy
    rule = g.domain_cache.get_rule(host)
AttributeError: 'NoneType' object has no attribute 'get_rule'

2021-04-14 22:18:05.945 [smart_router][DEBUG] connect to www.google.com:443 from:127.0.0.1:3308
2021-04-14 22:18:05.946 [smart_router][DEBUG] connect to www.google.com:443 from:127.0.0.1:3309
2021-04-14 22:18:05.947 [smart_router][ERROR] any err:AttributeError("'NoneType' object has no attribute 'get_rule'")
2021-04-14 22:18:05.948 [smart_router][DEBUG] connect to api.mousegesturesapi.com:443 from:127.0.0.1:3310
2021-04-14 22:18:05.949 [smart_router][ERROR] any err:AttributeError("'NoneType' object has no attribute 'get_rule'")

**Comment by miketwes** [comment]
> 按照教程设置了一下v6 在那个测试网站是 0/10 但是控制台报的错不一样了

无论用什么隧道怎么设置，要确保测试网站10／10正常输出才行

**Comment by fantasyado** [comment]
但是ping那个v6的测试地址可以ping通，  然后试了下原版的xx-net可以了，而且显示的可用ip 也是v6的

**Comment by miketwes** [comment]
> 但是ping那个v6的测试地址可以ping通， 然后试了下原版的xx-net可以了，而且显示的可用ip 也是v6的

ping那个v6的测试地址和用那个v6的测试地址测试v6是两个概念

**Comment by fantasyado** [comment]
那为啥xx-net可以用了。。

**Comment by miketwes** [comment]
> 那为啥xx-net可以用了。。

mini的Python是3.9.2

![2021-04-15_539x161](https://user-images.githubusercontent.com/6849681/114811666-1aeeeb80-9de1-11eb-8f20-660df420555a.png)

**Comment by fantasyado** [comment]
所以报的错和v6不通过没关系啊，看着就是空指针
