### ISSUE TITLE
TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by xuqinghan** [miketwes/XX-Net-mini#7]
win 10 x64
python 3.8.5 x64

上网时持续刷屏这些错误，但是并不影响上网，很好用！

Exception in thread Thread-277:
Traceback (most recent call last):
  File "D:\soft\tools\XX-Net-mini\code\default\smart_router\local\connect_manager.py", line 113, in create_connect
    sock.connect((ip, port))
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Python38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "D:\soft\tools\XX-Net-mini\code\default\smart_router\local\connect_manager.py", line 123, in create_connect
    g.ip_cache.report_connect_fail(ip, port)
  File "D:\soft\tools\XX-Net-mini\code\default\smart_router\local\host_records.py", line 360, in report_connect_fail
    if not is_network_ok(ip):
  File "D:\soft\tools\XX-Net-mini\code\default\smart_router\local\host_records.py", line 18, in is_network_ok
    return g.gae_proxy.check_local_network.is_ok(ip)
  File "D:\soft\tools\XX-Net-mini\code\default\gae_proxy\local\check_local_network.py", line 173, in is_ok
    elif "." in ip:
TypeError: a bytes-like object is required, not 'str'

**Comment by miketwes** [comment]
不知道什么原因, 我测试的时候没有出现以上错误信息,  可修改code/default/lib/noarch/xlog.py 中的 self.min_level = FATAL 以不显示错误信息
更新, 你可以试一下XX-Net-mini 4.5.2 应该不会出现以上错误信息
